[package]
name = "lib-2"
version = "1.23.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dep-1 = { path = "../dep-1" }
