on:
  push:
    branches:
      - main
name: release-please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@44c30b36230f7335e5da53e297d931807ccea116 # v3
        id: release
        with:
          command: manifest
      - run: echo "A release was created."
        if: ${{ steps.release.outputs.releases_created }}
      - run: echo ${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).headBranchName }}
    outputs:
      lib-1-tag_name: ${{ steps.release.outputs['crates/lib-1--tag_name'] }}
      lib-2-tag_name: ${{ steps.release.outputs['crates/lib-2--tag_name'] }}
      re_sign_commit: ${{ steps.release.outputs.pr }}
      release_branch_name: ${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).headBranchName }}

  # workaround because the Release-Please GHA does not sign GPG commits
  # we need to amend the head commit from the release PR.
  sign-release-commit:
    needs: [release]
    if: ${{ needs.release.outputs.re_sign_commit && needs.release.outputs.release_branch_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          ref: origin/${{ needs.release.outputs.release_branch_name }}
      - run: |
          RELEASE_COMMIT=$(git rev-parse origin/${{ needs.release.outputs.release_branch_name }})
          git commit --amend --no-edit -S -c $RELEASE_COMMIT
          git push --force-with-lease origin ${{ needs.release.outputs.release_branch_name }}

  release-lib-1:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.lib-1-tag_name }}
    steps:
      - run: echo "Release ${{ needs.release.outputs.lib-1-tag_name }} created for lib-1."
      - run: |
          echo 'tag_name: ${{ needs.release.outputs.lib-1-tag_name }}'
          RELEASE_TAG=${{ needs.release.outputs.lib-1-tag_name }}
          echo ${RELEASE_TAG%-v*}

  release-lib-2:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.lib-2-tag_name }}
    steps:
      - run: echo "Release ${{ needs.release.outputs.lib-2-tag_name }} created for lib-2."
      - run: |
          echo 'tag_name: ${{ needs.release.outputs.lib-2-tag_name }}'
          RELEASE_TAG=${{ needs.release.outputs.lib-2-tag_name }}
          echo ${RELEASE_TAG%-v*}
