on:
  push:
    branches:
      - main
name: release-please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@44c30b36230f7335e5da53e297d931807ccea116 # v3
        id: release
        with:
          command: manifest
      - run: echo "A release was created."
        if: ${{ steps.release.outputs.releases_created }}
    outputs:
      lib-1-tag_name: ${{ steps.release.outputs['crates/lib-1--tag_name'] }}
      lib-2-tag_name: ${{ steps.release.outputs['crates/lib-2--tag_name'] }}

  release-lib-1:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.lib-1-tag_name }}
    env:
      CRATE: lib-1
    steps:
      - run: echo "Release ${{ needs.release.outputs.$CRATE-tag_name }} created for $CRATE."
      - run: |
          echo 'tag_name: ${{ needs.release.outputs.$CRATE-tag_name }}'
          RELEASE_TAG=${{ needs.release.outputs.$CRATE-tag_name }}
          echo ${RELEASE_TAG%-v*}

  release-lib-2:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.lib-2-tag_name }}
    env:
      CRATE: lib-2
    steps:
      - run: echo "Release ${{ needs.release.outputs.$CRATE-tag_name }} created for $CRATE."
      - run: |
          echo 'tag_name: ${{ needs.release.outputs.$CRATE-tag_name }}'
          RELEASE_TAG=${{ needs.release.outputs.$CRATE-tag_name }}
          echo ${RELEASE_TAG%-v*}
